### ISSUE TITLE
Changing Turbo P-states will lead to a freeze.

### ISSUE THREAD

**Issue by ghost** [johkra/efi-undervolt#1]
Hey. 

Just an idea but have you tried disabling turbo setting(assuming it's possible) before setting the current P-state to [4](https://github.com/johkra/efi-undervolt/blob/24687924fbcae69cb76765deb5b7b01cdeb29682/undervolt.c#L79), and re-enabling it once done with setting all voltages ? In other words, ensure turbo P-states don't get triggered automatically* during the time you're trying to set their voltages. 

\* and I don't know if this can happen, I'm only guessing.

**EDIT:** re below, I don't have a 15h cpu (or efi capable bios) unfortunatelly, thus i cannot test.

**Comment by johkra** [comment]
I haven't tried. If you want to give it a go, check the CpbDis bit in MSRC001_0015. Details in https://support.amd.com/TechDocs/42301_15h_Mod_00h-0Fh_BKDG.pdf (search for CpbDis or MSRC001_0015).

See section 2.5.2.1.1 "Application Power Management (APM)" for details on the requirements for turbo boost. This should also give other methods for toggling turbo boost.

The documentation section mentions the need to have the bit unset on all cores to have Turbo enabled. Thus, setting the bit on a single core should disable turbo globally. I don't know how to execute code on different cores in the EFI environment should this become required.

**Comment by johkra** [comment]
I've tried and it works. The code is updated. Thanks for taking the time to file an issue!
